### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by TonitaN** [IOANNVOLZHSKIY/TFL#1]
@IOANNVOLZHSKIY , пока не сделаете, стягивать не буду.

**Comment by IOANNVOLZHSKIY** [comment]
gitignore добавлен, мусор из репозитория удален

**Comment by TonitaN** [comment]
@IOANNVOLZHSKIY , Чтобы не мусорить новыми issue и не привлекать толпу наших с вами поклонников, отметившихся на сообщении выше, пишу сразу тут:
на первом же тесте IndexOutOfBoundsException. Воспроизводить смысла нет - это была попытка сгенерировать случайную регулярку.

P.S. - Английский язык надо поправить, очень трудно понять, что сказано в логах.
